export type Language = 'fr' | 'en';
export const LANGUAGE_KEY = 'agent-village:language';

// UI copy only. Never translate or send conversation content to a remote service.
const english = {
  'Explorer les quartiers': 'Explore districts',
  'Quartier': 'District',
  'Vue du village': 'Village overview',
  'Tous les quartiers': 'All districts',
  'Explorer ce quartier': 'Explore this district',
  '{count} entrées de quartiers. Choisis un quartier pour voir ses chantiers.': '{count} district entrances. Choose a district to see its construction sites.',
  'Une parcelle par jalon. La maison commune résume le plan ; les agents y sont regroupés, sans jalon attribué.': 'One parcel per milestone. The common house summarizes the plan; agents gather there without an assigned milestone.',
  'Aucun jalon défini : ouvre la maison commune pour préparer le plan.': 'No milestones defined: open the common house to prepare the plan.',
  'Chantier sélectionné': 'Selected construction site',
  'Jalon validé': 'Validated milestone',
  'Jalon non validé': 'Unvalidated milestone',
  'Modifier ce jalon': 'Edit this milestone',
  'Cette parcelle reflète une validation explicite, pas un déploiement ni une estimation du travail restant.': 'This parcel reflects explicit validation, not deployment or an estimate of remaining work.',
  'Plan conservé · aucune conversation récente': 'Saved plan · no recent conversation',
  'Signal seul : le projet doit être identifié dans Codex ou Claude avant de définir son objectif.': 'Hook-only signal: the project must be identified in Codex or Claude before defining its goal.',
  '{count} sous-agents détectés': '{count} detected helpers',
  'historique ≠ activité': 'history ≠ activity',
  '{count} signaux de travail récents': '{count} recent work signals',
  'Agents et observations': 'Agents and observations',
  'Conversations principales': 'Lead conversations',
  'Sous-agents': 'Helpers',
  'Sous-agent': 'Helper',
  'Conversation principale': 'Lead conversation',
  'Conversation parente': 'Parent conversation',
  'Processus observés': 'Observed processes',
  '{count} en cours confirmés': '{count} confirmed working',
  'Détecté = présent dans les sources. Récent = signal récent. Confirmé = processus observé avec état récent, pas une garantie de travail continu.': 'Detected = present in sources. Recent = recent signal. Confirmed = observed process with recent state, not a guarantee of continuous work.',
  'Tokens, temps travaillé et durée restante : non mesurés par cette connexion.': 'Tokens, working time and remaining duration: not measured by this connection.',
  'Codex : sous-agents issus des liens parent-enfant de 60 conversations sur 7 jours ; 200 métadonnées maximum, profondeur 8, activité non confirmée.': 'Codex: helpers from parent-child links of 60 conversations over 7 days; at most 200 metadata records, depth 8, activity unconfirmed.',
  'Claude : sous-agents issus des hooks reçus depuis le démarrage ; conservation 30 minutes, historique incomplet.': 'Claude: helpers from hooks received since startup; retained for 30 minutes, incomplete history.',
  'Codex : couverture des sous-agents limitée par le plafond de collecte.': 'Codex: helper coverage limited by the collection cap.',
  'Codex : sous-agents partiellement ou non détectés ; la collecte des parents reste disponible.': 'Codex: helpers partially or not detected; parent collection remains available.',
  'Codex : index des sous-agents inaccessible': 'Codex: helper index unavailable',
  'Sous-agent Codex détecté dans l’index local · activité non confirmée': 'Codex helper detected in the local index · activity unconfirmed',
  'Plan à définir': 'Plan not defined',
  '{done}/{total} jalons validés': '{done}/{total} milestones validated',
  'Objectif et construction': 'Goal and construction',
  'OBJECTIF → CHANTIER': 'GOAL → BUILDING',
  '{count} restants': '{count} remaining',
  'Jalons validés': 'Validated milestones',
  'Contrôle local': 'Local check',
  'Validé par vous': 'Validated by you',
  'Un objectif stable et quelques jalons font avancer ce bâtiment. Les conversations seules ne prouvent pas la progression.': 'A stable goal and a few milestones build this house. Conversations alone do not prove progress.',
  'Modifier les jalons': 'Edit milestones',
  'Définir l’objectif': 'Define the goal',
  'Validation explicite, pas estimation automatique. Plan privé sur ce Mac. La carte suit sous 5 secondes.': 'Explicit validation, not an automatic estimate. Private plan on this Mac. The map updates within 5 seconds.',
  'Objectif final du projet': 'Final project goal',
  'Jalon {number}': 'Milestone {number}',
  'Valider le jalon {number}': 'Validate milestone {number}',
  'Note de validation {number}': 'Validation note {number}',
  'Ce que vous avez vérifié, et où.': 'What you checked, and where.',
  'Retirer le jalon {number}': 'Remove milestone {number}',
  'Retirer': 'Remove',
  'Ajouter un jalon': 'Add a milestone',
  'Cocher un jalon enregistre votre validation, pas une certification automatique des tests ou du déploiement.': 'Checking a milestone records your validation, not automatic certification of tests or deployment.',
  'Enregistrement…': 'Saving…',
  'Enregistrer le plan': 'Save the plan',
  'Annuler': 'Cancel',
  'Renseignez l’objectif, chaque jalon et une note pour chaque validation.': 'Enter the goal, every milestone title, and a note for each validation.',
  'Le plan a changé ailleurs. Votre brouillon est conservé. Annulez puis rouvrez le plan pour repartir de la dernière version.': 'The plan changed elsewhere. Your draft is preserved. Cancel and reopen the plan to start from the latest version.',
  'Enregistrement impossible. Votre brouillon est conservé. Réessayez.': 'Could not save. Your draft is preserved. Try again.',
  '{count} projets sur la carte. Bâtiments = jalons validés. Personnages = activité observée.': '{count} projects on the map. Buildings = validated milestones. People = observed activity.',
  'Objectifs privés illisibles. Aucune progression déduite.': 'Private goals unreadable. No progress inferred.',
  'Cliquer au sol pour marcher, sur une maison pour ouvrir son bilan.': 'Click the ground to walk, or a house to open its brief.',
  'Flèches : marcher · Maj+flèches : caméra · Échap : arrêter': 'Arrows: walk · Shift+arrows: camera · Escape: stop',
  'Capybara mousse — décor': 'Moss capybara — decorative',
  'Loutre cuivrée — décor': 'Copper otter — decorative',
  'Agent principal {tool}': '{tool} lead agent',
  'Sous-agent {tool}': '{tool} helper agent',
  'Agent {tool}, rôle inconnu': '{tool} agent, unknown role',
  'Conversation sans titre': 'Untitled conversation',
  '{count} sous-agents observés, {confirmed} en cours confirmés': '{count} observed helpers, {confirmed} confirmed working',
  'Activité détectée': 'Detected activity',
  'Activité récente': 'Recent activity',
  'Activité confirmée': 'Confirmed activity',
  'ACCÈS PERSONNEL': 'PERSONAL ACCESS',
  'Votre village, votre clé.': 'Your village, your key.',
  'Les projets restent derrière cette porte. Aucune conversation n’est chargée avant votre authentification.': 'Your projects stay behind this door. No conversations are loaded before you authenticate.',
  'Vérification de l’accès…': 'Checking access…',
  'Accès indisponible. Le village reste verrouillé.': 'Access unavailable. The village remains locked.',
  'Code absent, expiré ou incorrect. Relancez la configuration locale.': 'Setup code missing, expired or incorrect. Run local setup again.',
  'Authentification non terminée. Vous pouvez réessayer.': 'Authentication was not completed. You can try again.',
  'Code de configuration privé': 'Private setup code',
  'Première visite : utilisez le code local bootstrap.txt, puis créez votre clé d’accès. Ne partagez pas ce code.': 'First visit: use your local bootstrap.txt code, then create your passkey. Do not share this code.',
  'La configuration locale doit être lancée avant la première visite.': 'Run local setup before your first visit.',
  'Ce navigateur ne propose pas les clés d’accès. Ouvrez cette adresse dans Chrome ou Safari sur ce Mac.': 'This browser does not support passkeys. Open this address in Chrome or Safari on this Mac.',
  'Validation en cours…': 'Verifying…',
  'Ouvrir mon village': 'Open my village',
  'Créer ma clé d’accès': 'Create my passkey',
  'Clé d’accès requise · session de 30 minutes · aucun mot de passe stocké': 'Passkey required · 30-minute session · no stored password',
  'Cet accès est local à ce Mac. La démo GitHub publique ne contient pas vos conversations.': 'This access is local to this Mac. The public GitHub demo does not contain your conversations.',
  'Réessayer': 'Try again',
  'Verrouiller': 'Lock',
  'Journal du village': 'Village journal',
  'Votre point de départ': 'Start here',
  'À lire en premier': 'Read first',
  'Derniers signalements, pas des priorités déduites.': 'Recent reports, not inferred priorities.',
  'Lire le point de {name}': 'Read the update from {name}',
  'Blocage déclaré': 'Reported blocker',
  'Suite annoncée': 'Stated next step',
  'Compte rendu récent': 'Recent report',
  'Aucun nouveau compte rendu dans les sources lues. Les projets restent consultables.': 'No new reports in the scanned sources. Projects are still available.',
  'Sources et confidentialité': 'Sources and privacy',
  'Agent Village privé': 'Private Agent Village',
  'AGENT VILLAGE / LOCAL PRIVÉ': 'AGENT VILLAGE / LOCAL ONLY',
  'Mes projets, maintenant': 'My projects, right now',
  'projets': 'projects',
  'agents en cours': 'agents working',
  'Lu à': 'Read at',
  'actualisation 5 s': 'refreshes every 5 s',
  'Les données déjà lues restent affichées.': 'Previously read data remains visible.',
  'Projets connectés': 'Connected projects',
  'Revenir aux {count} projets suivis': 'Back to {count} tracked projects',
  'Voir aussi les {count} autres projets': 'Show the other {count} projects',
  'Rechercher un projet': 'Search projects',
  'Projet…': 'Project…',
  'Ouvrir {name}': 'Open {name}',
  'en cours': 'working',
  'en attente': 'waiting',
  'Derniers échanges': 'Recent updates',
  'nouveaux échanges': 'new updates',
  'Ouvrir les sessions': 'Open sessions',
  'Bâtiments de mes projets': 'My project buildings',
  '{count} projets récents sur la carte · recherche pour les autres. Chantier = activité, pas livraison.': '{count} recent projects on the map · search for the others. Construction means activity, not delivery.',
  'Les résumés sont les déclarations des agents, non des résultats vérifiés. Rien n’est envoyé à GitHub.': 'Summaries are agent reports, not verified results. Nothing is sent to GitHub.',
  'Les conversations sources restent dans leur langue d’origine.': 'Source conversations stay in their original language.',
  'Projet connecté': 'Connected project',
  'Fermer le projet': 'Close project',
  'Vue du projet': 'Project view',
  'Bilan': 'Brief',
  'Évolution': 'Timeline',
  'Conversations': 'Conversations',
  'Marquer comme lu': 'Mark as read',
  'nouveaux échanges depuis le dernier point de lecture.': 'new updates since the last reading point.',
  'Bilan du projet': 'Project brief',
  'Extraits des derniers comptes rendus par conversation, datés et consultables. Pas de pourcentage déduit de l’activité.': 'Excerpts from the latest report in each conversation, with dates and source links. Activity is not converted into a completion percentage.',
  'Aucun compte rendu textuel dans la fenêtre lue. Les sessions et leur état restent accessibles.': 'No text reports in the scanned window. Sessions and their states remain available.',
  'Fait — déclaré par les agents': 'Done — reported by agents',
  'Suite explicitement annoncée': 'Explicit next steps',
  'Blocages explicitement signalés': 'Explicitly reported blockers',
  'Ce qui a changé': 'What changed',
  'Chronologie réunie de toutes les conversations du projet. Les changements d’état seuls ne sont pas comptés comme du travail livré.': 'Combined timeline of all project conversations. State changes alone do not count as delivered work.',
  'Compte rendu': 'Report',
  'Demande': 'Request',
  'Terminal tmux :': 'tmux terminal:',
  'Dernière demande': 'Latest request',
  'Dernier compte rendu de l’agent': 'Latest agent report',
  'Historique récent': 'Recent history',
  'En cours': 'Working',
  'En attente': 'Waiting',
  'Sans activité récente': 'No recent activity',
  'État non confirmé': 'Unconfirmed state',
  'Recentrer le village': 'Reset village view',
  'Glisser ou utiliser les flèches pour explorer': 'Drag or use arrow keys to explore',
  'Village pixel {name}': '{name} pixel village',
  'Responsable {name}.': 'Owner {name}.',
  'Sans responsable.': 'No owner.',
  '7 jours · 24 derniers échanges par session · lecture bornée à 4 Mio par journal': '7 days · latest 24 updates per session · reads limited to 4 MiB per log',
  'Journal Codex local · état du dernier événement, pas une preuve de livraison': 'Local Codex log · latest event state, not proof of delivery',
  'Historique Claude · aucun processus associé confirmé': 'Claude history · no associated process confirmed',
  'Événement de cycle de vie local': 'Local lifecycle event',
  'Codex : certains journaux sont illisibles': 'Codex: some logs cannot be read',
  'Codex : index local inaccessible': 'Codex: local index unavailable',
  'Claude : certains journaux sont illisibles': 'Claude: some logs cannot be read',
  'Claude : journaux locaux inaccessibles': 'Claude: local logs unavailable',
  'Processus Claude présent · statut déclaré : {status}': 'Claude process present · reported state: {status}',
  'non fourni': 'not provided',
  'Vous': 'You',
  'Visiter le village': 'Visit the village',
  'Quitter la visite': 'Leave visit mode',
  'Apparence': 'Appearance',
  'Apparence de votre avatar': 'Your avatar appearance',
  'Fougère': 'Fern',
  'Soleil': 'Sun',
  'Iris': 'Iris',
  'Arrêter': 'Stop walking',
  'Destination inaccessible.': 'Destination is not reachable.',
  'Déplacement arrêté.': 'Movement stopped.',
  'Vous êtes arrivé.': 'You have arrived.',
  'Cliquer au sol pour marcher, sur une maison pour la visiter.': 'Click the ground to walk, or a house to visit it.',
  'Cliquer sur une maison pour ouvrir son bilan.': 'Click a house to open its brief.',
  'Flèches : marcher · Échap : arrêter · Glisser : caméra': 'Arrows: walk · Escape: stop · Drag: camera',
} as const;

export function translate(language: Language, key: keyof typeof english, values: Record<string, string | number> = {}): string {
  return (language === 'en' ? english[key] : key).replace(/\{(\w+)\}/g, (placeholder, name: string) => String(values[name] ?? placeholder));
}

// Server metadata predates localization. Translate only recognized system messages,
// never apply this to user titles, summaries, or conversation excerpts.
export function translateDiagnostic(language: Language, value: string): string {
  if (Object.hasOwn(english, value)) return translate(language, value as keyof typeof english);
  const prefix = 'Processus Claude présent · statut déclaré : ';
  if (value.startsWith(prefix)) {
    const status = value.slice(prefix.length);
    return translate(language, 'Processus Claude présent · statut déclaré : {status}', { status: status === 'non fourni' ? translate(language, 'non fourni') : status });
  }
  return value;
}

export function savedLanguage(): Language {
  try { return localStorage.getItem(LANGUAGE_KEY) === 'en' ? 'en' : 'fr'; }
  catch { return 'fr'; }
}
